 
version: '3.8'

services:
  web:
    build: .
    container_name: ci3-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: ci3-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci3docker
    ports:
      - "3306:3306"

volumes:
  db_data:
